language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  include:
    - php: 7.0
      env: SYMFONY_REQUIRE=3.4.* COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.4
      env: SYMFONY_REQUIRE=4.3.*
    - php: 7.4
      env: SYMFONY_REQUIRE=4.4.*
    - php: 7.4
      env: SYMFONY_REQUIRE=5.0.*

branches:
  only:
    - master
    # Build maintenance branches for older releases if needed. such branches should be named like "1.2"
    - '/^\d+\.\d+$/'

before_install:
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex
  - if ! [ -z "$SYMFONY_REQUIRE" ]; then composer config --unset platform.php; fi;

install:
  - composer update $COMPOSER_FLAGS --no-interaction
  - vendor/bin/simple-phpunit install

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/simple-phpunit
