language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"

branches:
  only:
    - master
    # Build maintenance branches for older releases if needed. such branches should be named like "1.2"
    - '/^\d+\.\d+$/'

before_script:
  # Install deps
  - composer update $COMPOSER_FLAGS --dev --prefer-source --no-interaction
  - bash -c "if [[ '$TRAVIS_PHP_VERSION' == '7.'* ]] ; then wget https://phar.phpunit.de/phpunit-5.7.phar; fi"

script:
  - bash -c "if [[ '$TRAVIS_PHP_VERSION' == '7.'* ]] ; then php phpunit-5.7.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' \< '7' ]; then phpunit; fi"
